### PR TITLE
latest sso test updates

### PR DESCRIPTION
**Pull request by bdecoste**

### CODE REVIEW

**Comment by alesj** [comment]
@bdecoste this needs some cleanup -- as you're using Fabric8 K8s client directly -- we want to hide that as impl detail under OpenShiftHandle.

Let me move this code under CE-ARQ ...

**Comment by bdecoste** [comment]
OK, will do. Thanks

**Comment by bdecoste** [comment]
Could you please re-review this and the ce-arq PR? I am not sure what to do with the native adapter - I can't find a way to do the exec.

**Comment by alesj** [comment]
Merged.

I'll see what can be done about the native adapter.

**Pull request closed without merging**
