### PR TITLE
Adding Decision Server Tests using JMS client - AMQ

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by alesj** [comment]
@spolti I get this when running the tests: https://gist.github.com/alesj/0df2e71ae876846beb72

**Comment by alesj** [comment]
Running just basic test, it works.
Running just AMQ, I get this: https://gist.github.com/alesj/34941f07e45a9044ce27

**Comment by spolti** [comment]
@alesj I got this issue also, seems the runinpod invoke the tests before the decision server get ready.

Decision server pod:
[0m[0m14:02:09,870 INFO  [org.kie.server.services.impl.KieServerImpl] (EJB default - 1) Container HelloRulesContainer (for release id org.openshift.quickstarts:decisionserver-hellorules:1.2.0.Final) successfully started


RunInpod:
[0m[33m14:01:23,980 WARN  [org.kie.server.client.impl.KieServicesClientImpl] (http-/10.1.3.11:8080-1) Unable to connect to server to get information about it due to Unexpected HTTP response code when requesting URI 'http://kie-app-fspolti.router.default.svc.cluster.local/kie-server/services/rest/server'! Error code: 503, message: <html><body><h1>503 Service Unavailable</h1>
185
No server is available to handle this request.
186
</body></html>

**Comment by alesj** [comment]
Hmm, can you check if the delay is waiting on the right pod(s)?

**Comment by spolti** [comment]
@alesj Bingo, in the AMQ case, the dalay is waiting fot the wrong pod:

Feb 17, 2016 4:59:45 PM org.jboss.arquillian.ce.utils.AbstractCEContainer$1 check
INFO: Pods are ready: [kie-app-amq-1-1vzpo]
Feb 17, 2016 4:59:45 PM org.jboss.arquillian.ce.utils.Containers delay
INFO: Checker [(Required pods: 1)] is ready.

where kie-app-amq-1-1vzpo is the amq broker, not the decision server. I changed the label to getr a unique name and worked, in this case deploymentConfig=kie-app, the other labels are the same for both pods.

**Pull request merged**
