### PR TITLE
Red hat repositories fix.  Added to superpom, easy to maintain theis …

### PR DESCRIPTION
**Pull request by jayunit100**
…way.  kiserver, jdg, and similar apps will need these to build.

### CODE REVIEW

**Comment by jayunit100** [comment]
Fixes #68 @rcernich

**Comment by jayunit100** [comment]
hmmm, getting an unauthorized error.... 

```
[ERROR] Failed to execute goal on project jdg-ce-testsuite: Could not resolve dependencies for project org.jboss.ce.testsuite:jdg-ce-testsuite:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.jboss.arquillian.container:arquillian-ce-shrinkwrap:jar:1.0.0-SNAPSHOT: Failed to read artifact descriptor for org.jboss.arquillian.container:arquillian-ce-shrinkwrap:jar:1.0.0-SNAPSHOT: Could not transfer artifact org.jboss.arquillian.container:arquillian-ce-shrinkwrap:pom:1.0.0-SNAPSHOT from/to 1rhat (https://repository.jboss.org/nexus/service/local/staging/deploy/maven2/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

**Comment by spolti** [comment]
you need to build the jboss-openshift/ce-arq manually, have you did it?

**Comment by jayunit100** [comment]
hmm, ok... no, i havent .   how do i do that?

**Comment by spolti** [comment]
git clone https://github.com/jboss-openshift/ce-arq.git

then build it: mvn clean install

"the instructions imply that the mvn clean package test sequence can be run without prerequisite compile steps?"

Thanks for your suggestion, I'll add it in the main readme file.

**Comment by jayunit100** [comment]
Similar error: 

```
➜  ce-arq git:(master) mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.arquillian.cube:arquillian-cube-openshift:jar is missing. @ org.jboss.arquillian.container:arquillian-ce-cube:[unknown-version], /Users/jayunit100/ce-arq/cube/pom.xml, line 47, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jboss.arquillian.container:arquillian-ce-cube:1.0.0-SNAPSHOT (/Users/jayunit100/ce-arq/cube/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.arquillian.cube:arquillian-cube-openshift:jar is missing. @ org.jboss.arquillian.container:arquillian-ce-cube:[unknown-version], /Users/jayunit100/ce-arq/cube/pom.xml, line 47, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by jayunit100** [comment]
@rcernich Any thoughts on how the CI is running this?  Maybe it bootstraps all the jars somehow?

**Comment by jayunit100** [comment]
ok this seems pretty close to consistent, cc @rcernich  ... i think combining this pom with the README should work in CI.  otherwise i guess the ci needs some customization in it that isnt in this code base.  let me know if any thoughts .  This is WIP, ill test more tomorrow on  a clean machine w/o any .m2 information., but seems to build for me now.

**Comment by jwendell** [comment]
Thanks for your suggestion. For the README instructions, it seems it's deprecated already as we have ce-arq 1.0 released. We have #138 to track that.

For the POM additions, we went in the opposite way, letting users to track repositories in their settings.xml.

**Pull request closed without merging**
