### PR TITLE
[CLOUD - 1136] - Create a test to cover the quartz timers for IPS

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by errantepiphany** [comment]
Looks good except,

1. Please change instances of `${template.repository}` and `${template.branch}` in ProcessServerPersistentTimersMySqlTest and ProcessServerPersistentTimersPostgreSqlTest to `${template.repository:jboss-openshift}` and `${template.branch:master}`, respectively.

2. Line 118 in `KieServerTestBase` ... Instead of checking if `(!clients.isEmpty())`, we should be checking for `(!clients.containsKey(baseURL))`. If it doesn't, create a matching `KieServicesConfiguration` and add it to the map. Then in either case, return the matching `KieServicesConfiguration` (pre-existing one or one just created).

**Comment by rcernich** [comment]
@errantepiphany, if this looks good to you, please push it up.  I've pushed the changes in openshift-quickstarts.

**Comment by errantepiphany** [comment]
@rcernich @spolti looks good now. I will process.

**Comment by errantepiphany** [comment]
pushed.

**Pull request merged**
